### ISSUE TITLE
Build with `INTERNAL_FILE_NML`?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/FMS#22]
Based on seeing @danholdaway enable this in JEDI-land, I remembered that long ago, I proposed enabling `INTERNAL_FILE_NML` in GEOS because @wmputman was having issues with `input.nml` at the time. But I guess that got lost in the days of CVS-to-Git transition. At the time I emailed/bothered @bensonr at GFDL about it asking:

> My question in regarding namelist reading in FMS. Bill Putman seems to
> be having intermittent issues with it, so I took a look. I noticed your
> name in the INTERNAL_FILE_NML codepath.
> 
> If you don't mind, can you help fill me in on what it does. My reading
> is that instead of say, all 96 processors reading the namelist everytime
> it's processed in FMS, FV3, microphysics, etc., only root would read it
> and then broadcast the results to an internal file. Is that correct?

and @bensonr replied:

> Your interpretation is correct.  To use the internal file, you only need:
> ```
>     use mpp_mod,   only:  input_nml_file
> 
>     read (input_nml_file, <namelist>, iostat=io)
>     ierr = check_nml_error (io, '<namelist>')
> ```
> If you are using multiple namelist files, you can clear and re-read a new namelist as needed using the mpp_mod::read_input_nml subroutine.

The current upstream FMS code does use it:
```cmake
option(INTERNAL_FILE_NML     "Enable compiler definition -DINTERNAL_FILE_NML"      ON)
```

I believe `INTERNAL_FILE_NML` is more performant at a large number of cores, so it seems a good thing to implement.

Obviously, I'd want @yvikhlya and @sanAkel to make sure we don't nuke the coupled model. I believe MOM5 has this as a macro/definition as well (I see `#ifdef INTERNAL_FILE_NML` in MOM5 source). 

I'm doing a test build of GEOSgcm with this now, but I think the fact that we only really use one `input.nml` in GEOS makes this simple to enable.

**Comment by bensonr** [comment]
@mathomp4 - in addition to the GFDL models, the UFS & GFS have been using the internal namelist read capability by default for a few years now.

**Comment by sanAkel** [comment]
@bensonr I am not aware if this would cause any issues with MOM6. Is that correct?

**Comment by mathomp4** [comment]
> @bensonr I am not aware if this would cause any issues with MOM6. Is that correct?

@sanAkel I don't think it should. MOM6 has no `#ifdef INTERNAL_FILE_NML` in its code, so it should be agnostic. MOM5 does have them, and I'm not sure what would happen if FMS enabled it and MOM5 didn't...maybe nothing?

**Comment by sanAkel** [comment]
> > @bensonr I am not aware if this would cause any issues with MOM6. Is that correct?
> 
> @sanAkel I don't think it should. MOM6 has no `#ifdef INTERNAL_FILE_NML` in its code, so it should be agnostic. 

Thank you @mathomp4, I am glad that it doesn't apply here!

**Comment by mathomp4** [comment]
@sanAkel @yvikhlya I have done my "normal" runs of MOM5 and MOM6 (and AMIP) and I see zero-diff between the current stock MOM5 and MOM6. I also get zero-diff with MOM5 whether both FMS and MOM5 enable `INTERNAL_FILE_NML` or just FMS. 

My only fear is that my "normal" runs of MOM5 and MOM6 are not as comprehensive as yours? Still, I'm going to make a PR for this change as it seems to be universally used with FMS per @bensonr

**Comment by bensonr** [comment]
Just to clarify, the use of INTERNAL_FILE_NML is not an either/or situation.  As part of mpp_init, the input_nml_file character variable is populated with the default input.nml regardless of the macro definition.  Within model codebase, you can utilize the input_nml_file to satisfy namelist parsing, but there is always still the option to utilize fortran open/read/close on a unit.  GFDL is in the process of removing the #ifdef from FMS and model code making the internal file read the default method for namelist parsing.

**Comment by sanAkel** [comment]
@bensonr Thanks for the details and explanation. Reg:

>GFDL is in the process of removing the #ifdef from FMS and model code making the internal file read the default method for namelist parsing.

This would be like in the _future_ versions of FMS?

**Comment by mathomp4** [comment]
Of course we are quite behind FMS. Fair warning to @bensonr and the fine folks at GFDL when GEOS moves to modern day FMS...so many questions coming your way! 😄

**Comment by bensonr** [comment]
@mathomp4 - I did see that before I started chiming in.  We'll be ready to answer any questions the NASA-GEOS team may have.

@sanAkel - current versions of NOAA-GFDL/FMS have been scrubbed of this particular macro.  The various component models maintained at GFDL are in the process of removing the macro and making the internal reads via the character variable the default.

**Comment by sanAkel** [comment]
@mathomp4, @bensonr, FWIW: I tested _optimized_ and _debug_ versions of GEOS with MOM6.

- optimized: no change in answers (from our current develop version, 1 day run)
- debug: runs (for 1 hour at 450s time step), as long as it runs, that's good enough (for me!)

**Note**: I used @mathomp4's [branch](https://github.com/GEOS-ESM/FMS/tree/temp-branch-for-santha) for ⤴️ tests and MAPL version: `v2.6.7`

**Comment by sanAkel** [comment]
@mathomp4,
can this be closed?

**Comment by mathomp4** [comment]
Oh. yeah. Closing!
