### ISSUE TITLE
Inconsistent FMS and MAPL constants

### ISSUE THREAD

**Issue by zhaobin74** [GEOS-ESM/FMS#3]
FMS uses 273.15 for KELVIN and MAPL uses 273.16 for MAPL_TICE. These two constants should be made the same; inconsistency caused conflicting melting/freezing conditions in coupled model.

**Comment by mathomp4** [comment]
I can definitely say that `KELVIN` is not used in FV3 as the word does not even occur there.

**Comment by mathomp4** [comment]
@zhaobin74 This should now be in the `Develop.cfg` of GEOSgcm.
